apiVersion: v1
data:
  config.yml: |
    listen:
      port: 4040
      address: "0.0.0.0"

    consul:
      enable: false

    namespaces:
      - name: nginx
        format: "$remote_addr - $remote_user [$time_local] \"$request\"$status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" $request_time"
        source:
          files:
            - /var/log/nginx/access.log
        labels:
          service: "nginx-thrift"
          environment: "production"
        relabel_configs:
          - source_labels: [request]
            regex: '^(\w+)\s+([^\s]+)\s+.*'
            target_label: method
            replacement: '${1}'
          - source_labels: [request]
            regex: '^(\w+)\s+([^\s]+)\s+.*'
            target_label: path
            replacement: '${2}'
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yml":"listen:\n  port: 4040\n  address: \"0.0.0.0\"\n\nconsul:\n  enable: false\n\nnamespaces:\n  - name: nginx\n    format: \"$remote_addr - $remote_user [$time_local] \\\"$request\\\" $status $body_bytes_sent \\\"$http_referer\\\" \\\"$http_user_agent\\\" \\\"$http_x_forwarded_for\\\" $request_time\"\n    source:\n      files:\n        - /var/log/nginx/access.log\n    labels:\n      service: \"nginx-thrift\"\n      environment: \"production\"\n    relabel_configs:\n      - source_labels: [request]\n        regex: '^(\\w+)\\s+([^\\s]+)\\s+.*'\n        target_label: method\n        replacement: '${1}'\n      - source_labels: [request]\n        regex: '^(\\w+)\\s+([^\\s]+)\\s+.*'\n        target_label: path\n        replacement: '${2}'\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/managed-by":"Helm","service":"nginx-thrift"},"name":"nginx-log-exporter-config","namespace":"default"}}
  creationTimestamp: "2025-09-17T16:11:31Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    service: nginx-thrift
  name: nginx-log-exporter-config
  namespace: social-network
  resourceVersion: "2631229"
  uid: eb2256e1-6e5b-4442-bdf2-4f6fd20d9a35
