apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: social-network
    meta.helm.sh/release-namespace: default
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
  creationTimestamp: "2025-09-11T07:11:35Z"
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
    service: user-timeline-redis
  name: user-timeline-redis
  namespace: social-network
  resourceVersion: "48026"
  uid: ed6543f5-bf59-47e1-9c38-1218576c48a1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      service: user-timeline-redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-09-11T09:37:16Z"
      creationTimestamp: null
      labels:
        app: user-timeline-redis
        service: user-timeline-redis
    spec:
      containers:
      - args:
        - /social-network-microservices/config/redis.conf
        image: docker.io/library/redis:6.2.4
        imagePullPolicy: IfNotPresent
        name: user-timeline-redis
        ports:
        - containerPort: 6379
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /social-network-microservices/config/redis.conf
          name: user-timeline-redis-config
          subPath: redis.conf
      - name: redis-exporter
        image: oliver006/redis_exporter:v1.48.0
        imagePullPolicy: IfNotPresent
        args:
        - "--redis.addr=redis://127.0.0.1:6379"
        ports:
        - containerPort: 9121
          name: metrics
        resources: {}
      dnsPolicy: ClusterFirst
      hostname: user-timeline-redis
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: user-timeline-redis
        name: user-timeline-redis-config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-09-11T07:11:41Z"
    lastUpdateTime: "2025-09-11T07:11:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-09-11T07:11:36Z"
    lastUpdateTime: "2025-09-11T09:37:28Z"
    message: ReplicaSet "user-timeline-redis-645bdd478d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

