apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-platform-sa
  namespace: chaos-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: chaos-platform
  name: chaos-platform-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-platform-rolebinding
  namespace: chaos-platform
subjects:
- kind: ServiceAccount
  name: chaos-platform-sa
  namespace: chaos-platform
roleRef:
  kind: Role
  name: chaos-platform-role
  apiGroup: rbac.authorization.k8s.io